### ISSUE TITLE
test RDS

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_SI4713#2]
reminder for future testing!

**Comment by kattni** [comment]
@ladyada Is this something that still needs to be tested?

**Comment by ladyada** [comment]
yeah i think so :/

**Comment by caternuson** [comment]
Picked one of these up a while back and decided to give this a check. Sorry to report - it does not work.

There are some Python 2-isms with `bytearray` usage:
https://github.com/adafruit/Adafruit_CircuitPython_SI4713/blob/a8d990a9c6792f5e9a709d279ad58dec3b282b02/adafruit_si4713.py#L460
But even with a quick patch to fix that, seem to only be getting the 1st 4 bytes set. Sanity checked with Arduino/UNO and that seemed to work OK.

I'll see if I can carve out some time to dig into this since I'm now kind of setup. Haven't even looked at datasheet yet. So for now, just reporting status quo.

**Comment by ladyada** [comment]
yep not toooo surprising, arduino works and it was a pita to get working so just copy that :D

**Comment by caternuson** [comment]
Fixed by #7 to work at least as well as Arduino version. Closing for now.

**Comment by ladyada** [comment]
huzzah!
